using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NTVXApi.Models
{
    public class BvxResponseModel
    {
        public string ebitdaMultiple { get; set; }
        public string ebitMultiple { get; set; }
        public string ebitda { get; set; }
        public string bvAsset { get; set; }
        public string fmvAsset { get; set; }
        public string goodwill { get; set; }
        public string stockassets { get; set; }
        public string ev { get; set; }
        public string cashclosing { get; set; }
        public string cashclosingper { get; set; }
        public string sellernote { get; set; }
        public string sellernoteper { get; set; }
        public string sellerball { get; set; }
        public string sellerballper { get; set; }
        public string noncompete { get; set; }
        public string noncompeteper { get; set; }
        public string personalgoodwill { get; set; }
        public string personalgoodwillper { get; set; }
        public string remcons { get; set; }
        public string remconsper { get; set; }
        public string evalue { get; set; }
        public string evalueper { get; set; }
        public string buyerequ { get; set; }
        public string buyerequper { get; set; }
        public string buyerroe { get; set; }
        public string buyerequity { get; set; }
        public string revolverterm { get; set; }
        public string overadvloan { get; set; }
        public string mezzfinan { get; set; }
        public string totalcapraised { get; set; }
        public string lessacquisition { get; set; }
        public string lessexcesscash { get; set; }
        public string cashtosellerclosing { get; set; }
        public string sales0 { get; set; }
        public string sales1 { get; set; }
        public string sales2 { get; set; }
        public string sales3 { get; set; }
        public string sales4 { get; set; }
        public string sales5 { get; set; }
        public string growth1 { get; set; }
        public string growth2 { get; set; }
        public string growth3 { get; set; }
        public string growth4 { get; set; }
        public string growth5 { get; set; }
        public string ebitda0 { get; set; }
        public string ebitda1 { get; set; }
        public string ebitda2 { get; set; }
        public string ebitda3 { get; set; }
        public string ebitda4 { get; set; }
        public string ebitda5 { get; set; }
        public string eper0 { get; set; }
        public string eper1 { get; set; }
        public string eper2 { get; set; }
        public string eper3 { get; set; }
        public string eper4 { get; set; }
        public string eper5 { get; set; }
        public string earnout1 { get; set; }
        public string earnout2 { get; set; }
        public string earnout3 { get; set; }
        public string earnout4 { get; set; }
        public string earnout5 { get; set; }
        public string remconspay1 { get; set; }
        public string remconspay2 { get; set; }
        public string remconspay3 { get; set; }
        public string remconspay4 { get; set; }
        public string remconspay5 { get; set; }
        public string ebitdaearnout1 { get; set; }
        public string ebitdaearnout2 { get; set; }
        public string ebitdaearnout3 { get; set; }
        public string ebitdaearnout4 { get; set; }
        public string ebitdaearnout5 { get; set; }
        public string depriciation1 { get; set; }
        public string depriciation2 { get; set; }
        public string depriciation3 { get; set; }
        public string depriciation4 { get; set; }
        public string depriciation5 { get; set; }
        public string noncompamor1 { get; set; }
        public string noncompamor2 { get; set; }
        public string noncompamor3 { get; set; }
        public string noncompamor4 { get; set; }
        public string noncompamor5 { get; set; }
        public string pergoodwillamor1 { get; set; }
        public string pergoodwillamor2 { get; set; }
        public string pergoodwillamor3 { get; set; }
        public string pergoodwillamor4 { get; set; }
        public string pergoodwillamor5 { get; set; }
        public string preconsamor1 { get; set; }
        public string preconsamor2 { get; set; }
        public string preconsamor3 { get; set; }
        public string preconsamor4 { get; set; }
        public string preconsamor5 { get; set; }
        public string acqcostamort1 { get; set; }
        public string acqcostamort2 { get; set; }
        public string acqcostamort3 { get; set; }
        public string acqcostamort4 { get; set; }
        public string acqcostamort5 { get; set; }
        public string goodwillamorttax1 { get; set; }
        public string goodwillamorttax2 { get; set; }
        public string goodwillamorttax3 { get; set; }
        public string goodwillamorttax4 { get; set; }
        public string goodwillamorttax5 { get; set; }
        public string totaldepandamort1 { get; set; }
        public string totaldepandamort2 { get; set; }
        public string totaldepandamort3 { get; set; }
        public string totaldepandamort4 { get; set; }
        public string totaldepandamort5 { get; set; }
        public string ebit1 { get; set; }
        public string ebit2 { get; set; }
        public string ebit3 { get; set; }
        public string ebit4 { get; set; }
        public string ebit5 { get; set; }
        public string intexprevolver1 { get; set; }
        public string intexprevolver2 { get; set; }
        public string intexprevolver3 { get; set; }
        public string intexprevolver4 { get; set; }
        public string intexprevolver5 { get; set; }
        public string intexptermloan1 { get; set; }
        public string intexptermloan2 { get; set; }
        public string intexptermloan3 { get; set; }
        public string intexptermloan4 { get; set; }
        public string intexptermloan5 { get; set; }
        public string intexpoveradvloan1 { get; set; }
        public string intexpoveradvloan2 { get; set; }
        public string intexpoveradvloan3 { get; set; }
        public string intexpoveradvloan4 { get; set; }
        public string intexpoveradvloan5 { get; set; }
        public string intexpmezzaninefinan1 { get; set; }
        public string intexpmezzaninefinan2 { get; set; }
        public string intexpmezzaninefinan3 { get; set; }
        public string intexpmezzaninefinan4 { get; set; }
        public string intexpmezzaninefinan5 { get; set; }
        public string intexpcapexloan1 { get; set; }
        public string intexpcapexloan2 { get; set; }
        public string intexpcapexloan3 { get; set; }
        public string intexpcapexloan4 { get; set; }
        public string intexpcapexloan5 { get; set; }
        public string intexpgapnote1 { get; set; }
        public string intexpgapnote2 { get; set; }
        public string intexpgapnote3 { get; set; }
        public string intexpgapnote4 { get; set; }
        public string intexpgapnote5 { get; set; }
        public string intexpgapballoonnote1 { get; set; }
        public string intexpgapballoonnote2 { get; set; }
        public string intexpgapballoonnote3 { get; set; }
        public string intexpgapballoonnote4 { get; set; }
        public string intexpgapballoonnote5 { get; set; }
        public string intexpnoncompete1 { get; set; }
        public string intexpnoncompete2 { get; set; }
        public string intexpnoncompete3 { get; set; }
        public string intexpnoncompete4 { get; set; }
        public string intexpnoncompete5 { get; set; }
        public string intexppersonalgoodwill1 { get; set; }
        public string intexppersonalgoodwill2 { get; set; }
        public string intexppersonalgoodwill3 { get; set; }
        public string intexppersonalgoodwill4 { get; set; }
        public string intexppersonalgoodwill5 { get; set; }
        public string intincomeoncash1 { get; set; }
        public string intincomeoncash2 { get; set; }
        public string intincomeoncash3 { get; set; }
        public string intincomeoncash4 { get; set; }
        public string intincomeoncash5 { get; set; }
        public string totalIntExpense1 { get; set; }
        public string totalIntExpense2 { get; set; }
        public string totalIntExpense3 { get; set; }
        public string totalIntExpense4 { get; set; }
        public string totalIntExpense5 { get; set; }
        public string taxableincome1 { get; set; }
        public string taxableincome2 { get; set; }
        public string taxableincome3 { get; set; }
        public string taxableincome4 { get; set; }
        public string taxableincome5 { get; set; }
        public string corpTaxesState1 { get; set; }
        public string corpTaxesState2 { get; set; }
        public string corpTaxesState3 { get; set; }
        public string corpTaxesState4 { get; set; }
        public string corpTaxesState5 { get; set; }
        public string corptexfederal1 { get; set; }
        public string corptexfederal2 { get; set; }
        public string corptexfederal3 { get; set; }
        public string corptexfederal4 { get; set; }
        public string corptexfederal5 { get; set; }
        public string netincome1 { get; set; }
        public string netincome2 { get; set; }
        public string netincome3 { get; set; }
        public string netincome4 { get; set; }
        public string netincome5 { get; set; }


        //Balance Sheet

        public string balancepurhaseCash { get; set; }
        public string balanceopeningCash { get; set; }
        public string balanceCashyear1 { get; set; }
        public string balanceCashyear2 { get; set; }
        public string balanceCashyear3 { get; set; }
        public string balanceCashyear4 { get; set; }
        public string balanceCashyear5 { get; set; }
        public string balancepurchaseAr { get; set; }
        public string balanceopeningAr { get; set; }
        public string balanceAryear1 { get; set; }
        public string balanceAryear2 { get; set; }
        public string balanceAryear3 { get; set; }
        public string balanceAryear4 { get; set; }
        public string balanceAryear5 { get; set; }
        public string balancepurchaseInventory { get; set; }
        public string balanceopeningInventory { get; set; }
        public string balanceInventoryyear1 { get; set; }
        public string balanceInventoryyear2 { get; set; }
        public string balanceInventoryyear3 { get; set; }
        public string balanceInventoryyear4 { get; set; }
        public string balanceInventoryyear5 { get; set; }
        public string balancepurchasemiscAssets { get; set; }
        public string balanceopeningmiscAssets { get; set; }
        public string balancemiscAssetsyear1 { get; set; }
        public string balancemiscAssetsyear2 { get; set; }
        public string balancemiscAssetsyear3 { get; set; }
        public string balancemiscAssetsyear4 { get; set; }
        public string balancemiscAssetsyear5 { get; set; }
        public string balancepurchaseFixedAssOld { get; set; }
        public string balanceopeningFixedAssOld { get; set; }
        public string balanceFixedAssOldyear1 { get; set; }
        public string balanceFixedAssOldyear2 { get; set; }
        public string balanceFixedAssOldyear3 { get; set; }
        public string balanceFixedAssOldyear4 { get; set; }
        public string balanceFixedAssOldyear5 { get; set; }
        public string balanceopeningADold { get; set; }
        public string balanceADoldYear1 { get; set; }
        public string balanceADoldYear2 { get; set; }
        public string balanceADoldYear3 { get; set; }
        public string balanceADoldYear4 { get; set; }
        public string balanceADoldYear5 { get; set; }
        public string balanceopenNewFixedAssets { get; set; }
        public string balanceNewFixedAssYear1 { get; set; }
        public string balanceNewFixedAssYear2 { get; set; }
        public string balanceNewFixedAssYear3 { get; set; }
        public string balanceNewFixedAssYear4 { get; set; }
        public string balanceNewFixedAssYear5 { get; set; }
        public string balanceopenADNewFixedAssets { get; set; }
        public string balanceADNewFixedAssyear1 { get; set; }
        public string balanceADNewFixedAssyear2 { get; set; }
        public string balanceADNewFixedAssyear3 { get; set; }
        public string balanceADNewFixedAssyear4 { get; set; }
        public string balanceADNewFixedAssyear5 { get; set; }
        public string balanceOpenAcquisitionExp { get; set; }
        public string balanceAcquisitionYear1 { get; set; }
        public string balanceAcquisitionYear2 { get; set; }
        public string balanceAcquisitionYear3 { get; set; }
        public string balanceAcquisitionYear4 { get; set; }
        public string balanceAcquisitionYear5 { get; set; }
        public string balanceOpenNonCompete { get; set; }
        public string balanceNonCompeteYear1 { get; set; }
        public string balanceNonCompeteYear2 { get; set; }
        public string balanceNonCompeteYear3 { get; set; }
        public string balanceNonCompeteYear4 { get; set; }
        public string balanceNonCompeteYear5 { get; set; }
        public string balanceopenPersonalGoodwill { get; set; }
        public string balancePersonalGoodwillYear1 { get; set; }
        public string balancePersonalGoodwillYear2 { get; set; }
        public string balancePersonalGoodwillYear3 { get; set; }
        public string balancePersonalGoodwillYear4 { get; set; }
        public string balancePersonalGoodwillYear5 { get; set; }
        public string balanceOpenRemCons1 { get; set; }
        public string balanceRemConsYear1 { get; set; }
        public string balanceRemConsYear2 { get; set; }
        public string balanceRemConsYear3 { get; set; }
        public string balanceRemConsYear4 { get; set; }
        public string balanceRemConsYear5 { get; set; }
        public string balanceOpenPreCons { get; set; }
        public string balancePrepaidConsYear1 { get; set; }
        public string balancePrepaidConsYear2 { get; set; }
        public string balancePrepaidConsYear3 { get; set; }
        public string balancePrepaidConsYear4 { get; set; }
        public string balancePrepaidConsYear5 { get; set; }
        public string balanceopenInvREntity { get; set; }
        public string balanceInvREntityYear1 { get; set; }
        public string balanceInvREntityYear2 { get; set; }
        public string balanceInvREntityYear3 { get; set; }
        public string balanceInvREntityYear4 { get; set; }
        public string balanceInvREntityYear5 { get; set; }
        public string balancepurchGoodwill { get; set; }
        public string balanceopenGoodwillRes { get; set; }
        public string balanceGoodwillYear1 { get; set; }
        public string balanceGoodwillYear2 { get; set; }
        public string balanceGoodwillYear3 { get; set; }
        public string balanceGoodwillYear4 { get; set; }
        public string balanceGoodwillYear5 { get; set; }
        public string balancepurchTotalAssets { get; set; }
        public string balanceopenTotalAssets { get; set; }
        public string balanceTotalAssetsYear1 { get; set; }
        public string balanceTotalAssetsYear2 { get; set; }
        public string balanceTotalAssetsYear3 { get; set; }
        public string balanceTotalAssetsYear4 { get; set; }
        public string balanceTotalAssetsYear5 { get; set; }
        public string balancepurchAPaccured { get; set; }
        public string balanceopenARAccured { get; set; }
        public string balanceARAccuredYear1 { get; set; }
        public string balanceARAccuredYear2 { get; set; }
        public string balanceARAccuredYear3 { get; set; }
        public string balanceARAccuredYear4 { get; set; }
        public string balanceARAccuredYear5 { get; set; }
        public string balancepurchOtherMiscLiab { get; set; }
        public string balanceopenOtherMiscLiab { get; set; }
        public string balanceOtherMiscLiabYear1 { get; set; }
        public string balanceOtherMiscLiabYear2 { get; set; }
        public string balanceOtherMiscLiabYear3 { get; set; }
        public string balanceOtherMiscLiabYear4 { get; set; }
        public string balanceOtherMiscLiabYear5 { get; set; }
        public string balancepurchNonOperLiab { get; set; }
        public string balanceopenNonOperLiab { get; set; }
        public string balanceNonOperLiabYear1 { get; set; }
        public string balanceNonOperLiabYear2 { get; set; }
        public string balanceNonOperLiabYear3 { get; set; }
        public string balanceNonOperLiabYear4 { get; set; }
        public string balanceNonOperLiabYear5 { get; set; }
        public string balanceopenRevolver { get; set; }
        public string balanceRevolverYear1 { get; set; }
        public string balanceRevolverYear2 { get; set; }
        public string balanceRevolverYear3 { get; set; }
        public string balanceRevolverYear4 { get; set; }
        public string balanceRevolverYear5 { get; set; }
        public string balanceopenTermLoan { get; set; }
        public string balanceTermLoanYear1 { get; set; }
        public string balanceTermLoanYear2 { get; set; }
        public string balanceTermLoanYear3 { get; set; }
        public string balanceTermLoanYear4 { get; set; }
        public string balanceTermLoanYear5 { get; set; }
        public string balanceopenOverAdvLoan { get; set; }
        public string balanceOverAdvLoan1 { get; set; }
        public string balanceOverAdvLoan2 { get; set; }
        public string balanceOverAdvLoan3 { get; set; }
        public string balanceOverAdvLoan4 { get; set; }
        public string balanceOverAdvLoan5 { get; set; }
        public string balanceopenMezzFinancing { get; set; }
        public string balanceMezzFinancingYear1 { get; set; }
        public string balanceMezzFinancingYear2 { get; set; }
        public string balanceMezzFinancingYear3 { get; set; }
        public string balanceMezzFinancingYear4 { get; set; }
        public string balanceMezzFinancingYear5 { get; set; }
        public string balanceopenGapNote { get; set; }
        public string balanceGapNoteYear1 { get; set; }
        public string balanceGapNoteYear2 { get; set; }
        public string balanceGapNoteYear3 { get; set; }
        public string balanceGapNoteYear4 { get; set; }
        public string balanceGapNoteYear5 { get; set; }
        public string balanceopenGapBallonNote { get; set; }
        public string balanceGapBallonNoteYear1 { get; set; }
        public string balanceGapBallonNoteYear2 { get; set; }
        public string balanceGapBallonNoteYear3 { get; set; }
        public string balanceGapBallonNoteYear4 { get; set; }
        public string balanceGapBallonNoteYear5 { get; set; }
        public string balanceopenCapExLoan { get; set; }
        public string balanceCapExLoanYear1 { get; set; }
        public string balanceCapExLoanYear2 { get; set; }
        public string balanceCapExLoanYear3 { get; set; }
        public string balanceCapExLoanYear4 { get; set; }
        public string balanceCapExLoanYear5 { get; set; }
        public string balanceopenRemNonCompPayment { get; set; }
        public string balanceRemNonComPaymentYear1 { get; set; }
        public string balanceRemNonComPaymentYear2 { get; set; }
        public string balanceRemNonComPaymentYear3 { get; set; }
        public string balanceRemNonComPaymentYear4 { get; set; }
        public string balanceRemNonComPaymentYear5 { get; set; }
        public string balanceopenRemPersonalGWpay { get; set; }
        public string balanceRemPersonalGWpayYear1 { get; set; }
        public string balanceRemPersonalGWpayYear2 { get; set; }
        public string balanceRemPersonalGWpayYear3 { get; set; }
        public string balanceRemPersonalGWpayYear4 { get; set; }
        public string balanceRemPersonalGWpayYear5 { get; set; }
        public string balanceopenRemConsPay { get; set; }
        public string balanceRemConssPayYear1 { get; set; }
        public string balanceRemConssPayYear2 { get; set; }
        public string balanceRemConssPayYear3 { get; set; }
        public string balanceRemConssPayYear4 { get; set; }
        public string balanceRemConssPayYear5 { get; set; }
        public string balanceopenNonOperatingLiab { get; set; }
        public string balanceNonOperatingLiabYear1 { get; set; }
        public string balanceNonOperatingLiabYear2 { get; set; }
        public string balanceNonOperatingLiabYear3 { get; set; }
        public string balanceNonOperatingLiabYear4 { get; set; }
        public string balanceNonOperatingLiabYear5 { get; set; }
        public string balancepurchTotalLiab { get; set; }
        public string balanceopenTotalLiab { get; set; }
        public string balanceTotalLiabYear1 { get; set; }
        public string balanceTotalLiabYear2 { get; set; }
        public string balanceTotalLiabYear3 { get; set; }
        public string balanceTotalLiabYear4 { get; set; }
        public string balanceTotalLiabYear5 { get; set; }
        public string balancepurchRetainedEarning { get; set; }
        public string balanceopenRetaiedEarning { get; set; }
        public string balanceRetainedEarningYr1 { get; set; }
        public string balanceRetainedEarningYr2 { get; set; }
        public string balanceRetainedEarningYr3 { get; set; }
        public string balanceRetainedEarningYr4 { get; set; }
        public string balanceRetainedEarningYr5 { get; set; }
        public string balanceopenAddCapital { get; set; }
        public string balanceAddCapitalYear1 { get; set; }
        public string balanceAddCapitalYear2 { get; set; }
        public string balanceAddCapitalYear3 { get; set; }
        public string balanceAddCapitalYear4 { get; set; }
        public string balanceAddCapitalYear5 { get; set; }
        public string balanceopenDisTax { get; set; }
        public string balanceDisTaxYear1 { get; set; }
        public string balanceDisTaxYear2 { get; set; }
        public string balanceDisTaxYear3 { get; set; }
        public string balanceDisTaxYear4 { get; set; }
        public string balanceDisTaxYear5 { get; set; }
        public string balanceopenDividend { get; set; }
        public string balanceDividendYear1 { get; set; }
        public string balanceDividendYear2 { get; set; }
        public string balanceDividendYear3 { get; set; }
        public string balanceDividendYear4 { get; set; }
        public string balanceDividendYear5 { get; set; }
        public string balancepurchCommonStk { get; set; }
        public string balanceopenCommonStk { get; set; }
        public string balanceCommonStkYear1 { get; set; }
        public string balanceCommonStkYear2 { get; set; }
        public string balanceCommonStkYear3 { get; set; }
        public string balanceCommonStkYear4 { get; set; }
        public string balanceCommonStkYear5 { get; set; }
        public string balancepurchTotalEquity { get; set; }
        public string balanceopenTotalEquity { get; set; }
        public string balanceTotalEquYear1 { get; set; }
        public string balanceTotalEquYear2 { get; set; }
        public string balanceTotalEquYear3 { get; set; }
        public string balanceTotalEquYear4 { get; set; }
        public string balanceTotalEquYear5 { get; set; }
        public string balancepurchTotalLiabEqu { get; set; }
        public string balanceopenTotalLiabEqu { get; set; }
        public string balanceTotalLiabEquYear1 { get; set; }
        public string balanceTotalLiabEquYear2 { get; set; }
        public string balanceTotalLiabEquYear3 { get; set; }
        public string balanceTotalLiabEquYear4 { get; set; }
        public string balanceTotalLiabEquYear5 { get; set; }


        // Free Cash Flow

        public string freeNetIncomeYr1 { get; set; }
        public string freeNetIncomeYr2 { get; set; }
        public string freeNetIncomeYr3 { get; set; }
        public string freeNetIncomeYr4 { get; set; }
        public string freeNetIncomeYr5 { get; set; }
        public string freedeprYr1 { get; set; }
        public string freedeprYr2 { get; set; }
        public string freedeprYr3 { get; set; }
        public string freedeprYr4 { get; set; }
        public string freedeprYr5 { get; set; }
        public string freeNonCompAmortYr1 { get; set; }
        public string freeNonCompAmortYr2 { get; set; }
        public string freeNonCompAmortYr3 { get; set; }
        public string freeNonCompAmortYr4 { get; set; }
        public string freeNonCompAmortYr5 { get; set; }
        public string freePerGoodwillAmortYr1 { get; set; }
        public string freePerGoodwillAmortYr2 { get; set; }
        public string freePerGoodwillAmortYr3 { get; set; }
        public string freePerGoodwillAmortYr4 { get; set; }
        public string freePerGoodwillAmortYr5 { get; set; }
        public string freePreConsAmortYr1 { get; set; }
        public string freePreConsAmortYr2 { get; set; }
        public string freePreConsAmortYr3 { get; set; }
        public string freePreConsAmortYr4 { get; set; }
        public string freePreConsAmortYr5 { get; set; }
        public string freeAcqCostAmort1 { get; set; }
        public string freeAcqCostAmort2 { get; set; }
        public string freeAcqCostAmort3 { get; set; }
        public string freeAcqCostAmort4 { get; set; }
        public string freeAcqCostAmort5 { get; set; }
        public string freeGoddwillAmortYr1 { get; set; }
        public string freeGoddwillAmortYr2 { get; set; }
        public string freeGoddwillAmortYr3 { get; set; }
        public string freeGoddwillAmortYr4 { get; set; }
        public string freeGoddwillAmortYr5 { get; set; }
        public string freeWCchangeYr1 { get; set; }
        public string freeWCchangeYr2 { get; set; }
        public string freeWCchangeYr3 { get; set; }
        public string freeWCchangeYr4 { get; set; }
        public string freeWCchangeYr5 { get; set; }
        public string freeRevPaydownWCYr1 { get; set; }
        public string freeRevPaydownWCYr2 { get; set; }
        public string freeRevPaydownWCYr3 { get; set; }
        public string freeRevPaydownWCYr4 { get; set; }
        public string freeRevPaydownWCYr5 { get; set; }
        public string freeTermLoanPayYr1 { get; set; }
        public string freeTermLoanPayYr2 { get; set; }
        public string freeTermLoanPayYr3 { get; set; }
        public string freeTermLoanPayYr4 { get; set; }
        public string freeTermLoanPayYr5 { get; set; }
        public string freeOverAdvLoanPayYr1 { get; set; }
        public string freeOverAdvLoanPayYr2 { get; set; }
        public string freeOverAdvLoanPayYr3 { get; set; }
        public string freeOverAdvLoanPayYr4 { get; set; }
        public string freeOverAdvLoanPayYr5 { get; set; }
        public string freeMezzFinanPayYr1 { get; set; }
        public string freeMezzFinanPayYr2 { get; set; }
        public string freeMezzFinanPayYr3 { get; set; }
        public string freeMezzFinanPayYr4 { get; set; }
        public string freeMezzFinanPayYr5 { get; set; }
        public string freeGapNotePayYr1 { get; set; }
        public string freeGapNotePayYr2 { get; set; }
        public string freeGapNotePayYr3 { get; set; }
        public string freeGapNotePayYr4 { get; set; }
        public string freeGapNotePayYr5 { get; set; }
        public string freeGapBalloonNotePayYr1 { get; set; }
        public string freeGapBalloonNotePayYr2 { get; set; }
        public string freeGapBalloonNotePayYr3 { get; set; }
        public string freeGapBalloonNotePayYr4 { get; set; }
        public string freeGapBalloonNotePayYr5 { get; set; }
        public string freeRemNonCompPayYr1 { get; set; }
        public string freeRemNonCompPayYr2 { get; set; }
        public string freeRemNonCompPayYr3 { get; set; }
        public string freeRemNonCompPayYr4 { get; set; }
        public string freeRemNonCompPayYr5 { get; set; }
        public string freeRemPersGoodwillPayYr1 { get; set; }
        public string freeRemPersGoodwillPayYr2 { get; set; }
        public string freeRemPersGoodwillPayYr3 { get; set; }
        public string freeRemPersGoodwillPayYr4 { get; set; }
        public string freeRemPersGoodwillPayYr5 { get; set; }
        public string freeCapExpYr1 { get; set; }
        public string freeCapExpYr2 { get; set; }
        public string freeCapExpYr3 { get; set; }
        public string freeCapExpYr4 { get; set; }
        public string freeCapExpYr5 { get; set; }
        public string freeCapExpBorrowYr1 { get; set; }
        public string freeCapExpBorrowYr2 { get; set; }
        public string freeCapExpBorrowYr3 { get; set; }
        public string freeCapExpBorrowYr4 { get; set; }
        public string freeCapExpBorrowYr5 { get; set; }
        public string freeCapExpPayYr1 { get; set; }
        public string freeCapExpPayYr2 { get; set; }
        public string freeCapExpPayYr3 { get; set; }
        public string freeCapExpPayYr4 { get; set; }
        public string freeCapExpPayYr5 { get; set; }
        public string freeEarnOutPayPriceAdjYr1 { get; set; }
        public string freeEarnOutPayPriceAdjYr2 { get; set; }
        public string freeEarnOutPayPriceAdjYr3 { get; set; }
        public string freeEarnOutPayPriceAdjYr4 { get; set; }
        public string freeEarnOutPayPriceAdjYr5 { get; set; }
        public string freeDisShareholdertaxyr1 { get; set; }
        public string freeDisShareholdertaxyr2 { get; set; }
        public string freeDisShareholdertaxyr3 { get; set; }
        public string freeDisShareholdertaxyr4 { get; set; }
        public string freeDisShareholdertaxyr5 { get; set; }
        public string freeOpeCashFlowBusiYr1 { get; set; }
        public string freeOpeCashFlowBusiYr2 { get; set; }
        public string freeOpeCashFlowBusiYr3 { get; set; }
        public string freeOpeCashFlowBusiYr4 { get; set; }
        public string freeOpeCashFlowBusiYr5 { get; set; }
        public string freeOpeCashFlowRealEstateYr1 { get; set; }
        public string freeOpeCashFlowRealEstateYr2 { get; set; }
        public string freeOpeCashFlowRealEstateYr3 { get; set; }
        public string freeOpeCashFlowRealEstateYr4 { get; set; }
        public string freeOpeCashFlowRealEstateYr5 { get; set; }
        public string freeOperCashFlowTotalYr1 { get; set; }
        public string freeOperCashFlowTotalYr2 { get; set; }
        public string freeOperCashFlowTotalYr3 { get; set; }
        public string freeOperCashFlowTotalYr4 { get; set; }
        public string freeOperCashFlowTotalYr5 { get; set; }
        public string freebeginCashBalYr1 { get; set; }
        public string freebeginCashBalYr2 { get; set; }
        public string freebeginCashBalYr3 { get; set; }
        public string freebeginCashBalYr4 { get; set; }
        public string freebeginCashBalYr5 { get; set; }
        public string freeOperCashFlowYr1 { get; set; }
        public string freeOperCashFlowYr2 { get; set; }
        public string freeOperCashFlowYr3 { get; set; }
        public string freeOperCashFlowYr4 { get; set; }
        public string freeOperCashFlowYr5 { get; set; }
        public string freeOpeCashReqYr1 { get; set; }
        public string freeOpeCashReqYr2 { get; set; }
        public string freeOpeCashReqYr3 { get; set; }
        public string freeOpeCashReqYr4 { get; set; }
        public string freeOpeCashReqYr5 { get; set; }
        public string freeCashRevEndYr1 { get; set; }
        public string freeCashRevEndYr2 { get; set; }
        public string freeCashRevEndYr3 { get; set; }
        public string freeCashRevEndYr4 { get; set; }
        public string freeCashRevEndYr5 { get; set; }
        public string freeb4BorrowingYr1 { get; set; }
        public string freeb4BorrowingYr2 { get; set; }
        public string freeb4BorrowingYr3 { get; set; }
        public string freeb4BorrowingYr4 { get; set; }
        public string freeb4BorrowingYr5 { get; set; }
        public string freeAvailCreditLineyr1 { get; set; }
        public string freeAvailCreditLineyr2 { get; set; }
        public string freeAvailCreditLineyr3 { get; set; }
        public string freeAvailCreditLineyr4 { get; set; }
        public string freeAvailCreditLineyr5 { get; set; }
        public string freeAddRevolverYr1 { get; set; }
        public string freeAddRevolverYr2 { get; set; }
        public string freeAddRevolverYr3 { get; set; }
        public string freeAddRevolverYr4 { get; set; }
        public string freeAddRevolverYr5 { get; set; }
        public string freeBVXCashFlowYr1 { get; set; }
        public string freeBVXCashFlowYr2 { get; set; }
        public string freeBVXCashFlowYr3 { get; set; }
        public string freeBVXCashFlowYr4 { get; set; }
        public string freeBVXCashFlowYr5 { get; set; }
        public string freeAddCapContributeYr1 { get; set; }
        public string freeAddCapContributeYr2 { get; set; }
        public string freeAddCapContributeYr3 { get; set; }
        public string freeAddCapContributeYr4 { get; set; }
        public string freeAddCapContributeYr5 { get; set; }
        public string freeDividendDistrRegYr1 { get; set; }
        public string freeDividendDistrRegYr2 { get; set; }
        public string freeDividendDistrRegYr3 { get; set; }
        public string freeDividendDistrRegYr4 { get; set; }
        public string freeDividendDistrRegYr5 { get; set; }
        public string freeAddOverAdvLoanPayYr1 { get; set; }
        public string freeAddOverAdvLoanPayYr2 { get; set; }
        public string freeAddOverAdvLoanPayYr3 { get; set; }
        public string freeAddOverAdvLoanPayYr4 { get; set; }
        public string freeAddOverAdvLoanPayYr5 { get; set; }
        public string freeAddRevolverPayYr1 { get; set; }
        public string freeAddRevolverPayYr2 { get; set; }
        public string freeAddRevolverPayYr3 { get; set; }
        public string freeAddRevolverPayYr4 { get; set; }
        public string freeAddRevolverPayYr5 { get; set; }
        public string freeAddTremloanPayYr1 { get; set; }
        public string freeAddTremloanPayYr2 { get; set; }
        public string freeAddTremloanPayYr3 { get; set; }
        public string freeAddTremloanPayYr4 { get; set; }
        public string freeAddTremloanPayYr5 { get; set; }
        public string freeAddNewCapExPayYr1 { get; set; }
        public string freeAddNewCapExPayYr2 { get; set; }
        public string freeAddNewCapExPayYr3 { get; set; }
        public string freeAddNewCapExPayYr4 { get; set; }
        public string freeAddNewCapExPayYr5 { get; set; }
        public string freeAddgapNotePayYr1 { get; set; }
        public string freeAddgapNotePayYr2 { get; set; }
        public string freeAddgapNotePayYr3 { get; set; }
        public string freeAddgapNotePayYr4 { get; set; }
        public string freeAddgapNotePayYr5 { get; set; }
        public string freeDiviDistrAddYr1 { get; set; }
        public string freeDiviDistrAddYr2 { get; set; }
        public string freeDiviDistrAddYr3 { get; set; }
        public string freeDiviDistrAddYr4 { get; set; }
        public string freeDiviDistrAddYr5 { get; set; }
        public string freeCapitalFusionYr1 { get; set; }
        public string freeCapitalFusionYr2 { get; set; }
        public string freeCapitalFusionYr3 { get; set; }
        public string freeCapitalFusionYr4 { get; set; }
        public string freeCapitalFusionYr5 { get; set; }
        public string freeChangeinCashYr1 { get; set; }
        public string freeChangeinCashYr2 { get; set; }
        public string freeChangeinCashYr3 { get; set; }
        public string freeChangeinCashYr4 { get; set; }
        public string freeChangeinCashYr5 { get; set; }

        //Cash Flow Statement

        public string stmtNetIncomeYr1 { get; set; }
        public string stmtNetIncomeYr2 { get; set; }
        public string stmtNetIncomeYr3 { get; set; }
        public string stmtNetIncomeYr4 { get; set; }
        public string stmtNetIncomeYr5 { get; set; }
        public string stmtDepriciationYr1 { get; set; }
        public string stmtDepriciationYr2 { get; set; }
        public string stmtDepriciationYr3 { get; set; }
        public string stmtDepriciationYr4 { get; set; }
        public string stmtDepriciationYr5 { get; set; }
        public string stmtnonCompAmortyr1 { get; set; }
        public string stmtnonCompAmortyr2 { get; set; }
        public string stmtnonCompAmortyr3 { get; set; }
        public string stmtnonCompAmortyr4 { get; set; }
        public string stmtnonCompAmortyr5 { get; set; }
        public string stmtPerGoodwillAmortYr1 { get; set; }
        public string stmtPerGoodwillAmortYr2 { get; set; }
        public string stmtPerGoodwillAmortYr3 { get; set; }
        public string stmtPerGoodwillAmortYr4 { get; set; }
        public string stmtPerGoodwillAmortYr5 { get; set; }
        public string stmtPreConAmortYr1 { get; set; }
        public string stmtPreConAmortYr2 { get; set; }
        public string stmtPreConAmortYr3 { get; set; }
        public string stmtPreConAmortYr4 { get; set; }
        public string stmtPreConAmortYr5 { get; set; }
        public string stmtAcqCostAmortYr1 { get; set; }
        public string stmtAcqCostAmortYr2 { get; set; }
        public string stmtAcqCostAmortYr3 { get; set; }
        public string stmtAcqCostAmortYr4 { get; set; }
        public string stmtAcqCostAmortYr5 { get; set; }
        public string stmtGoodwillAmortYr1 { get; set; }
        public string stmtGoodwillAmortYr2 { get; set; }
        public string stmtGoodwillAmortYr3 { get; set; }
        public string stmtGoodwillAmortYr4 { get; set; }
        public string stmtGoodwillAmortYr5 { get; set; }
        public string stmtWChangeYr1 { get; set; }
        public string stmtWChangeYr2 { get; set; }
        public string stmtWChangeYr3 { get; set; }
        public string stmtWChangeYr4 { get; set; }
        public string stmtWChangeYr5 { get; set; }
        public string stmtOperActivityYr1 { get; set; }
        public string stmtOperActivityYr2 { get; set; }
        public string stmtOperActivityYr3 { get; set; }
        public string stmtOperActivityYr4 { get; set; }
        public string stmtOperActivityYr5 { get; set; }
        public string stmtCapitalExpYr1 { get; set; }
        public string stmtCapitalExpYr2 { get; set; }
        public string stmtCapitalExpYr3 { get; set; }
        public string stmtCapitalExpYr4 { get; set; }
        public string stmtCapitalExpYr5 { get; set; }
        public string stmtPriceAdjYr1 { get; set; }
        public string stmtPriceAdjYr2 { get; set; }
        public string stmtPriceAdjYr3 { get; set; }
        public string stmtPriceAdjYr4 { get; set; }
        public string stmtPriceAdjYr5 { get; set; }
        public string stmtRemNonCompPayYr1 { get; set; }
        public string stmtRemNonCompPayYr2 { get; set; }
        public string stmtRemNonCompPayYr3 { get; set; }
        public string stmtRemNonCompPayYr4 { get; set; }
        public string stmtRemNonCompPayYr5 { get; set; }
        public string stmtRemPerGWPayYr1 { get; set; }
        public string stmtRemPerGWPayYr2 { get; set; }
        public string stmtRemPerGWPayYr3 { get; set; }
        public string stmtRemPerGWPayYr4 { get; set; }
        public string stmtRemPerGWPayYr5 { get; set; }
        public string stmtInvActYr1 { get; set; }
        public string stmtInvActYr2 { get; set; }
        public string stmtInvActYr3 { get; set; }
        public string stmtInvActYr4 { get; set; }
        public string stmtInvActYr5 { get; set; }
        public string stmtAddRevolverYr1 { get; set; }
        public string stmtAddRevolverYr2 { get; set; }
        public string stmtAddRevolverYr3 { get; set; }
        public string stmtAddRevolverYr4 { get; set; }
        public string stmtAddRevolverYr5 { get; set; }
        public string stmtRevPayWCYr1 { get; set; }
        public string stmtRevPayWCYr2 { get; set; }
        public string stmtRevPayWCYr3 { get; set; }
        public string stmtRevPayWCYr4 { get; set; }
        public string stmtRevPayWCYr5 { get; set; }
        public string stmtAddRevPayYr1 { get; set; }
        public string stmtAddRevPayYr2 { get; set; }
        public string stmtAddRevPayYr3 { get; set; }
        public string stmtAddRevPayYr4 { get; set; }
        public string stmtAddRevPayYr5 { get; set; }
        public string stmtTermLoanPayYr1 { get; set; }
        public string stmtTermLoanPayYr2 { get; set; }
        public string stmtTermLoanPayYr3 { get; set; }
        public string stmtTermLoanPayYr4 { get; set; }
        public string stmtTermLoanPayYr5 { get; set; }
        public string stmtAddTermLoanpayYr1 { get; set; }
        public string stmtAddTermLoanpayYr2 { get; set; }
        public string stmtAddTermLoanpayYr3 { get; set; }
        public string stmtAddTermLoanpayYr4 { get; set; }
        public string stmtAddTermLoanpayYr5 { get; set; }
        public string stmtOverAdvLoanPayYr1 { get; set; }
        public string stmtOverAdvLoanPayYr2 { get; set; }
        public string stmtOverAdvLoanPayYr3 { get; set; }
        public string stmtOverAdvLoanPayYr4 { get; set; }
        public string stmtOverAdvLoanPayYr5 { get; set; }
        public string stmtAddOverAdvLoanPayYr1 { get; set; }
        public string stmtAddOverAdvLoanPayYr2 { get; set; }
        public string stmtAddOverAdvLoanPayYr3 { get; set; }
        public string stmtAddOverAdvLoanPayYr4 { get; set; }
        public string stmtAddOverAdvLoanPayYr5 { get; set; }
        public string stmtMezzFinanPayYr1 { get; set; }
        public string stmtMezzFinanPayYr2 { get; set; }
        public string stmtMezzFinanPayYr3 { get; set; }
        public string stmtMezzFinanPayYr4 { get; set; }
        public string stmtMezzFinanPayYr5 { get; set; }
        public string stmtGapNotePayYr1 { get; set; }
        public string stmtGapNotePayYr2 { get; set; }
        public string stmtGapNotePayYr3 { get; set; }
        public string stmtGapNotePayYr4 { get; set; }
        public string stmtGapNotePayYr5 { get; set; }
        public string stmtGapBalloonPayYr1 { get; set; }
        public string stmtGapBalloonPayYr2 { get; set; }
        public string stmtGapBalloonPayYr3 { get; set; }
        public string stmtGapBalloonPayYr4 { get; set; }
        public string stmtGapBalloonPayYr5 { get; set; }
        public string stmtAddGapNotePayYr1 { get; set; }
        public string stmtAddGapNotePayYr2 { get; set; }
        public string stmtAddGapNotePayYr3 { get; set; }
        public string stmtAddGapNotePayYr4 { get; set; }
        public string stmtAddGapNotePayYr5 { get; set; }
        public string stmtCapExpBorrowYr1 { get; set; }
        public string stmtCapExpBorrowYr2 { get; set; }
        public string stmtCapExpBorrowYr3 { get; set; }
        public string stmtCapExpBorrowYr4 { get; set; }
        public string stmtCapExpBorrowYr5 { get; set; }
        public string stmtCapExpPayYr1 { get; set; }
        public string stmtCapExpPayYr2 { get; set; }
        public string stmtCapExpPayYr3 { get; set; }
        public string stmtCapExpPayYr4 { get; set; }
        public string stmtCapExpPayYr5 { get; set; }
        public string stmtAddNewCapExPayYr1 { get; set; }
        public string stmtAddNewCapExPayYr2 { get; set; }
        public string stmtAddNewCapExPayYr3 { get; set; }
        public string stmtAddNewCapExPayYr4 { get; set; }
        public string stmtAddNewCapExPayYr5 { get; set; }
        public string stmtAddCapContributeYr1 { get; set; }
        public string stmtAddCapContributeYr2 { get; set; }
        public string stmtAddCapContributeYr3 { get; set; }
        public string stmtAddCapContributeYr4 { get; set; }
        public string stmtAddCapContributeYr5 { get; set; }
        public string stmtDividendDisRegYr1 { get; set; }
        public string stmtDividendDisRegYr2 { get; set; }
        public string stmtDividendDisRegYr3 { get; set; }
        public string stmtDividendDisRegYr4 { get; set; }
        public string stmtDividendDisRegYr5 { get; set; }
        public string stmtDividendDisAddYr1 { get; set; }
        public string stmtDividendDisAddYr2 { get; set; }
        public string stmtDividendDisAddYr3 { get; set; }
        public string stmtDividendDisAddYr4 { get; set; }
        public string stmtDividendDisAddYr5 { get; set; }
        public string stmtDisrShareTaxYr1 { get; set; }
        public string stmtDisrShareTaxYr2 { get; set; }
        public string stmtDisrShareTaxYr3 { get; set; }
        public string stmtDisrShareTaxYr4 { get; set; }
        public string stmtDisrShareTaxYr5 { get; set; }
        public string stmtFinanActivitiesYr1 { get; set; }
        public string stmtFinanActivitiesYr2 { get; set; }
        public string stmtFinanActivitiesYr3 { get; set; }
        public string stmtFinanActivitiesYr4 { get; set; }
        public string stmtFinanActivitiesYr5 { get; set; }
        public string stmtCashBusinessYr1 { get; set; }
        public string stmtCashBusinessYr2 { get; set; }
        public string stmtCashBusinessYr3 { get; set; }
        public string stmtCashBusinessYr4 { get; set; }
        public string stmtCashBusinessYr5 { get; set; }
        public string stmtCashEstateYr1 { get; set; }
        public string stmtCashEstateYr2 { get; set; }
        public string stmtCashEstateYr3 { get; set; }
        public string stmtCashEstateYr4 { get; set; }
        public string stmtCashEstateYr5 { get; set; }
        public string stmtTotalinCashYr1 { get; set; }
        public string stmtTotalinCashYr2 { get; set; }
        public string stmtTotalinCashYr3 { get; set; }
        public string stmtTotalinCashYr4 { get; set; }
        public string stmtTotalinCashYr5 { get; set; }
        public string stmtBeginCashBalYr1 { get; set; }
        public string stmtBeginCashBalYr2 { get; set; }
        public string stmtBeginCashBalYr3 { get; set; }
        public string stmtBeginCashBalYr4 { get; set; }
        public string stmtBeginCashBalYr5 { get; set; }
        public string stmtEndCashBalYr1 { get; set; }
        public string stmtEndCashBalYr2 { get; set; }
        public string stmtEndCashBalYr3 { get; set; }
        public string stmtEndCashBalYr4 { get; set; }
        public string stmtEndCashBalYr5 { get; set; }

        //ROI Page

        public string roiOrigEquInvYr0 { get; set; }
        public string roiExitMultipleYr5 { get; set; }
        public string roiPlusCashRetainYr5 { get; set; }
        public string roiClosingCostExitYr5 { get; set; }
        public string roiStateYr5 { get; set; }
        public string roiLessNonOperLiabYr5 { get; set; }
        public string roiTerminalValYr5 { get; set; }
        public string roiShareholderYr1 { get; set; }
        public string roiShareholderYr2 { get; set; }
        public string roiShareholderYr3 { get; set; }
        public string roiShareholderYr4 { get; set; }
        public string roiShareholderYr5 { get; set; }
        public string roiIRSYr1 { get; set; }
        public string roiIRSYr2 { get; set; }
        public string roiIRSYr3 { get; set; }
        public string roiIRSYr4 { get; set; }
        public string roiIRSYr5 { get; set; }
        public string roiAddCapContribution1 { get; set; }
        public string roiAddCapContribution2 { get; set; }
        public string roiAddCapContribution3 { get; set; }
        public string roiAddCapContribution4 { get; set; }
        public string roiAddCapContribution5 { get; set; }
        public string roiDividendDist1 { get; set; }
        public string roiDividendDist2 { get; set; }
        public string roiDividendDist3 { get; set; }
        public string roiDividendDist4 { get; set; }
        public string roiDividendDist5 { get; set; }
        public string roiSdivPreTaxYr1 { get; set; }
        public string roiSdivPreTaxYr2 { get; set; }
        public string roiSdivPreTaxYr3 { get; set; }
        public string roiSdivPreTaxYr4 { get; set; }
        public string roiSdivPreTaxYr5 { get; set; }
        public string roiUndistributeYr1 { get; set; }
        public string roiUndistributeYr2 { get; set; }
        public string roiUndistributeYr3 { get; set; }
        public string roiUndistributeYr4 { get; set; }
        public string roiUndistributeYr5 { get; set; }
        public string roiblankYr1 { get; set; }
        public string roiblankYr2 { get; set; }
        public string roiblankYr3 { get; set; }
        public string roiblankYr4 { get; set; }
        public string roiblankYr5 { get; set; }
        public string roiByerCashFlowyr1 { get; set; }
        public string roiByerCashFlowyr2 { get; set; }
        public string roiByerCashFlowyr3 { get; set; }
        public string roiByerCashFlowyr4 { get; set; }
        public string roiByerCashFlowyr5 { get; set; }
        public string roiMezzCashFlowYr0 { get; set; }
        public string roiMezzCashFlowYr1 { get; set; }
        public string roiMezzCashFlowYr2 { get; set; }
        public string roiMezzCashFlowYr3 { get; set; }
        public string roiMezzCashFlowYr4 { get; set; }
        public string roiMezzCashFlowYr5 { get; set; }
        public string roiByerPreTaxyr0 { get; set; }
        public string roiByerPreTaxyr1 { get; set; }
        public string roiByerPreTaxyr2 { get; set; }
        public string roiByerPreTaxyr3 { get; set; }
        public string roiByerPreTaxyr4 { get; set; }
        public string roiByerPreTaxyr5 { get; set; }
        public string roiByerPreTaxROE { get; set; }
        public string roiMezzFinancing0 { get; set; }
        public string roiIntExpMezzFinanYr0 { get; set; }
        public string roiIntExpMezzFinanYr1 { get; set; }
        public string roiIntExpMezzFinanYr2 { get; set; }
        public string roiIntExpMezzFinanYr3 { get; set; }
        public string roiIntExpMezzFinanYr4 { get; set; }
        public string roiIntExpMezzFinanYr5 { get; set; }
        public string roiMezzPrincipalAmortYr0 { get; set; }
        public string roiMezzPrincipalAmortYr1 { get; set; }
        public string roiMezzPrincipalAmortYr2 { get; set; }
        public string roiMezzPrincipalAmortYr3 { get; set; }
        public string roiMezzPrincipalAmortYr4 { get; set; }
        public string roiMezzPrincipalAmortYr5 { get; set; }
        public string roiMezzRemPrincePayYr0 { get; set; }
        public string roiMezzRemPrincePayYr1 { get; set; }
        public string roiMezzRemPrincePayYr2 { get; set; }
        public string roiMezzRemPrincePayYr3 { get; set; }
        public string roiMezzRemPrincePayYr4 { get; set; }
        public string roiMezzRemPrincePayYr5 { get; set; }
        public string roiMezzSharePreTaxYr0 { get; set; }
        public string roiMezzSharePreTaxYr1 { get; set; }
        public string roiMezzSharePreTaxYr2 { get; set; }
        public string roiMezzSharePreTaxYr3 { get; set; }
        public string roiMezzSharePreTaxYr4 { get; set; }
        public string roiMezzSharePreTaxYr5 { get; set; }
        public string roiMezzaPreTaxCasshFlowYr0 { get; set; }
        public string roiMezzaPreTaxCasshFlowYr1 { get; set; }
        public string roiMezzaPreTaxCasshFlowYr2 { get; set; }
        public string roiMezzaPreTaxCasshFlowYr3 { get; set; }
        public string roiMezzaPreTaxCasshFlowYr4 { get; set; }
        public string roiMezzaPreTaxCasshFlowYr5 { get; set; }
        public string roiActualMezzPreTaxROIYr0 { get; set; }
        public string roiExpectMezzYr0 { get; set; }

        // download file reference

        //public string DownloadServerFileName { get; set; }

        // download file names
        public string DownloadServerFileName { get; set; }
    }
}